[package]
name = "bin-encrypt-decrypt"
version = "1.3.0"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = "A high-performance binary encryption and decryption library that supports customizable character sets beyond Base64."
keywords = ["binaryencryption", "decryption", "customcharset", "highperformance", "base64alternative"]
repository = "https://github.com/ltpp-universe/bin-crypt-decrypt"

[dependencies]
ltpp-output = "1.1.1"
std-macro-extensions = "0.16.0"
